# SUPPLEMENTARY CODE FOR THE MASTER PROJECT: 
# Speculative Bubbles, Financial Crises and Contagion

# This script determines the presence of contagion effects generated by the subprime crisis.

# The pre-crisis conditional correlation.
pre.crisis.dcc <- c()
for(i in 1:624)
 {
  pre.crisis.dcc <- c(pre.crisis.dcc, rcor(pre.crisis.dcc.garch.fit)[,,i][1, 2])
 }

# The crisis conditional correlation.
crisis.dcc <- c()
for(i in 1:579)
 {
  crisis.dcc <- c(crisis.dcc, rcor(crisis.dcc.garch.fit)[,,i][1, 2])
 }

# Welch two sample t-test.
t.test(pre.crisis.dcc, crisis.dcc)

# Wilcoxon rank sum test with continuity correction.
wilcox.test(pre.crisis.dcc, crisis.dcc)